### ISSUE TITLE
GUIs for Docker Registry

### ISSUE THREAD

**Issue by jacksgt** [vision-it/vision-registry#2]
* [Portainer](https://github.com/portainer/portainer)
* [Docker Registry Browser](https://github.com/klausmeyer/docker-registry-browser)
* [Docker Registry Manager](https://github.com/snagles/docker-registry-manager)

_just a collection of some links..._

**Comment by martialblog** [comment]
@jacksgt  Fixed with BOW?

**Comment by martialblog** [comment]
Gonna have a look at Portainer, which would also be useful for Docker Schwarm

**Comment by martialblog** [comment]
I think we rather want Portus http://port.us.org/features.html

**Comment by martialblog** [comment]
Gitlab Container Registry https://about.gitlab.com/2016/05/23/gitlab-container-registry/

**Comment by jacksgt** [comment]
Considering we will have fewer hosts in the DMZ in the future and assuming we were to run Gitlab Container Registry (which by now is available in the core edition of Gitlab), we could get away with 'manually' copying images to DMZ hosts.

```
$ docker image pull webshop:latest
$ docker image save webshop:latest | ssh v10 docker image load
Loaded image: webshop:latest
$ ssh v10 docker image ls
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
webshop                             latest              ef44a9e7ed62        25 minutes ago      798MB
```

Copying the image from my machine to v10 was surprisingly quick (33s), even for the massive (800MB) webshop image.

Of course, this job (copying) could the be automated in our deploy tasks. I'm kind of fond of this idea.

**Comment by martialblog** [comment]
@jacksgt Spricht was dagegen die Diskussion intern weiter zu führen?

**Comment by jacksgt** [comment]
https://puppet.com/products/puppet-container-registry

**Comment by martialblog** [comment]
Siehe Internes Ticket
